name: release

"on":
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [bleeding]
  workflow_dispatch:

jobs:

  release:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: detailobsessed/ci-components/.github/workflows/semantic-release-uv.yml@main
    with:
      python-version: "3.14"
    secrets: inherit
